#
# Host: localhost    Database: ironwork_nova
#--------------------------------------------------------
# Server version	3.23.36

#
# Dumping data for table '_mkclassids'
#

# keg: removed this, should always be generated by MiddleKit

#
# Dumping data for table 'arrivalevent'
#


#
# Dumping data for table 'battleevent'
#


#
# Dumping data for table 'createroutingevent'
#


#
# Dumping data for table 'deathprobeevent'
#


#
# Dumping data for table 'departureevent'
#


#
# Dumping data for table 'fierydeathevent'
#


#
# Dumping data for table 'game'
#

# Doesn't really matter though because the test case needs
#   to set the start and end times manually, otherwise the game will be over before it starts
# It runs at 50,000 times normal speed
INSERT INTO game (gameId, 	timeCompression, 	lastActionTime,	eventCounter, 	startTime, 				endTime, 				deathProbeCost, spyProbeCost, factoryCost, speedCost, battlePowerCost, rangeCost, probeShieldCost, deathShieldCost) 
VALUES 			 (1,		50000,				NULL,			0,				'2003-05-05 09:38:23',	'2003-05-05 09:43:23',	200,10,5,500,100,100,10,200);

#
# Dumping data for table 'garrison'
#


#
# Dumping data for table 'globallock'
#


#
# Dumping data for table 'globalproductionevent'
#

INSERT INTO globalproductionevent (globalProductionEventId, gameId, executionTime, eventCounter, playerId, status) VALUES (1,8589934593,'2003-05-05 09:41:16',-1,21474836484,'Pending');

#
# Dumping data for table 'player'
#

INSERT INTO player (playerId, gameId, userId, name, wealth, battlePower, range, speed) VALUES (1,8589934593,12884901889,'kevin',250,100,15,0.5);
INSERT INTO player (playerId, gameId, userId, name, wealth, battlePower, range, speed) VALUES (2,8589934593,12884901890,'scott',250,100,15,0.5);
INSERT INTO player (playerId, gameId, userId, name, wealth, battlePower, range, speed) VALUES (3,8589934593,12884901891,'dave',250,100,15,0.5);
INSERT INTO player (playerId, gameId, userId, name, wealth, battlePower, range, speed) VALUES (4,8589934593,12884901892,'Nobody',250,100,10,0.5);

#
# Dumping data for table 'productionevent'
#


#
# Dumping data for table 'purchasebattlepowerevent'
#


#
# Dumping data for table 'purchasedeathshieldevent'
#


#
# Dumping data for table 'purchasefactoriesevent'
#


#
# Dumping data for table 'purchaseprobeshieldevent'
#


#
# Dumping data for table 'purchaserangeevent'
#


#
# Dumping data for table 'purchasespeedevent'
#


#
# Dumping data for table 'removeroutingevent'
#


#
# Dumping data for table 'routing'
#


#
# Dumping data for table 'spyprobeevent'
#


#
# Dumping data for table 'star'
#

INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (1,8589934593,'Aladfar',4,74,15,11,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (2,8589934593,'Aludra',7,42,13,3,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (3,8589934593,'Pleione',7,52,15,5,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (4,8589934593,'Fornacis',8,23,14,13,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (5,8589934593,'Kitalpha',8,28,14,14,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (6,8589934593,'Deneb El Okab',9,20,15,4,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (7,8589934593,'Antares',12,70,14,19,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (8,8589934593,'Zaurak',13,88,17,16,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (9,8589934593,'Sarin',16,24,13,9,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (10,8589934593,'dave',16,75,10,250,0,0,0,21474836483,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (11,8589934593,'Alula Australis',17,9,14,11,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (12,8589934593,'Azelfafage',17,80,16,13,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (13,8589934593,'Ed Asich',18,33,12,1,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (14,8589934593,'Zaniah',21,48,16,7,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (15,8589934593,'Hamal',23,65,15,13,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (16,8589934593,'Andromeda Nebula',26,49,12,12,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (17,8589934593,'Zuben Elgenubi',30,72,16,9,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (18,8589934593,'Tyl',31,35,19,18,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (19,8589934593,'Acrux A',32,57,20,10,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (20,8589934593,'Miram',34,16,20,6,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (21,8589934593,'Situla',34,95,15,17,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (22,8589934593,'Avior',40,82,13,9,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (23,8589934593,'Alzirr',41,24,12,17,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (24,8589934593,'Dabih Minor',41,69,14,16,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (25,8589934593,'Polaris',45,5,18,0,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (26,8589934593,'Castor B',45,91,14,13,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (27,8589934593,'Alderamin',46,45,11,9,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (28,8589934593,'scott',47,11,10,250,0,0,0,21474836482,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (29,8589934593,'Bogardus',47,60,13,16,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (30,8589934593,'Mira',50,17,15,6,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (31,8589934593,'Arkab Prior',52,30,16,11,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (32,8589934593,'Beid',52,52,13,3,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (33,8589934593,'Matar',52,76,16,3,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (34,8589934593,'Albireo',58,87,15,18,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (35,8589934593,'Alfirk',59,38,12,3,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (36,8589934593,'Rasalhague',62,7,14,4,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (37,8589934593,'kevin',62,51,10,250,0,0,0,21474836481,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (38,8589934593,'Wasat',62,64,15,18,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (39,8589934593,'Fieht',66,15,14,15,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (40,8589934593,'Zavijava',68,73,16,15,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (41,8589934593,'Menkib',69,33,12,3,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (42,8589934593,'Seginus',71,45,12,12,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (43,8589934593,'Sadalbari',71,90,18,18,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (44,8589934593,'Marj',79,67,17,15,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (45,8589934593,'Asellus Australis',80,78,11,10,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (46,8589934593,'Zuben Eschamali',81,24,17,15,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (47,8589934593,'Alfecca Meridiana',82,13,15,13,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (48,8589934593,'Acamar',85,33,14,19,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (49,8589934593,'Wazn',87,52,18,7,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (50,8589934593,'Acrux B',89,84,13,4,0,0,0,21474836484,NULL,0);
INSERT INTO star (starId, gameId, name, x, y, wealth, numShips, numFactories, hasSpyShield, hasDeathShield, ownerId, homeWorldOfId, isDead) VALUES (51,8589934593,'Dziban',90,69,12,15,0,0,0,21474836484,NULL,0);

#
# Dumping data for table 'triggerdefinition'
#

INSERT INTO triggerdefinition (triggerDefinitionId, className) VALUES (1,'nova.trigger.battleMessage.BattleMessageTrigger');

#
# Dumping data for table 'triggerinstance'
#

#
# Dumping data for table 'user'
#

INSERT INTO user (userId, name, password, email) VALUES (1,'kevin','kevin','kgilpin@yahoo.com');
INSERT INTO user (userId, name, password, email) VALUES (2,'scott','scott','scott@westslopesoftware.com');
INSERT INTO user (userId, name, password, email) VALUES (3,'dave','dave','daved@alum.mit.edu');
INSERT INTO user (userId, name, password, email) VALUES (4,'Nobody','nobody','');

