'''
GenFieryDeathEvent.py
Tue Mar 29 11:44:59 2005
Generated by MiddleKit.
'''

# MK attribute caches for setFoo() methods
_gameAttr = None
_executionTimeAttr = None
_eventCounterAttr = None
_playerAttr = None
_statusAttr = None
_departureEventAttr = None

import types
from mx import DateTime
import sys
from os.path import dirname
sys.path.insert(0, dirname(dirname(dirname(__file__))))
from nova.Event import Event
del sys.path[0]

from types import InstanceType, LongType
from MiddleKit.Run.SQLObjectStore import ObjRefError



class GenFieryDeathEvent(Event):

	def __init__(self):
		Event.__init__(self)
		self._departureEvent = None

	def construct(self, game, executionTime, player, departureEvent):
		# Construct the FieryDeathEvent with all the required attributes that do not have default values
		self.setGame( game )
		self.setExecutionTime( executionTime )
		self.setPlayer( player )
		self.setDepartureEvent( departureEvent )

	def departureEvent(self):
		if self._departureEvent is not None and type(self._departureEvent) is not InstanceType:
			try:
				self.__dict__['_departureEvent'] = self._mk_store.fetchObjRef(self._departureEvent)
			except ObjRefError, e:
				self.__dict__['_departureEvent'] = self.objRefErrorWasRaised(e, 'FieryDeathEvent', 'departureEvent')
		return self._departureEvent

	def setDepartureEvent(self, value):
		assert value is not None
		if value is not None and type(value) is not LongType:
			if not type(value) is InstanceType:
				raise TypeError, 'expecting InstanceType, but got value %r of type %r instead' % (value, type(value))
			from nova.DepartureEvent import DepartureEvent
			if not isinstance(value, DepartureEvent):
				raise TypeError, 'expecting DepartureEvent, but got value %r of type %r instead' % (value, type(value))

		# set the attribute
		origValue = self._departureEvent
		self._departureEvent = value

		# MiddleKit machinery
		self._mk_changed = 1  # @@ original semantics, but I think this should be under "if not self._mk_initing..."
		if not self._mk_initing and self._mk_serialNum>0 and value is not origValue:
			global _departureEventAttr
			if _departureEventAttr is None:
				_departureEventAttr = self.klass().lookupAttr('departureEvent')
				if not _departureEventAttr.shouldRegisterChanges():
					_departureEventAttr = 0
			if _departureEventAttr:
				# Record that it has been changed
				if self._mk_changedAttrs is None:
					self._mk_changedAttrs = {} # maps name to attribute
				self._mk_changedAttrs['departureEvent'] = _departureEventAttr  # changedAttrs is a set
				# Tell ObjectStore it happened
				self._mk_store.objectChanged(self)

